version: '2'
services:
  core:
    container_name: voecom-core
    image: anclaev/voecom-core:latest
    restart: always
    depends_on:
      - db
      - auth
      - rabbitmq
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=api.voecom.ru
      - VIRTUAL_PORT=3007
      - LETSENCRYPT_HOST=api.voecom.ru
    networks:
      - nginx-proxy-net
      - net

  auth:
    container_name: voecom-auth
    image: anclaev/voecom-auth:latest
    restart: always
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    networks:
      - net

  db:
    container_name: voecom-db
    image: postgres:latest
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256"
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
    networks:
      - net
    ports:
      - 8083:8080

  rabbitmq:
    image: rabbitmq:3-management
    container_name: voecom-rabbitmq
    env_file:
      - .env
    volumes:
      - rmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net

networks:
  nginx-proxy-net:
    external: true

  net:
    driver: bridge

volumes:
  data: {}
  rmq: {}
