version: '2'
services:
  api:
    container_name: voecom-core
    image: anclaev/voecom:latest
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=api.voecom.ru
      - VIRTUAL_PORT=3003
      - LETSENCRYPT_HOST=api.voecom.ru
    networks:
      - nginx-proxy-net
      - net

  db:
    container_name: voecom-db
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USERNAME=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
    networks:
      - net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: voecom-rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: vhost
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net

networks:
  nginx-proxy-net:
    external: true

  net:
    driver: bridge

volumes:
  data: {}
