name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Restore cached npm dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: npm-dependencies-${{ hashFiles('yarn.lock') }}

      - run: yarn install --immutable

      - name: Cache npm dependencies
        id: cache-dependencies-save
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ steps.cache-dependencies-restore.outputs.cache-primary-key }}

      - uses: nrwl/nx-set-shas@v3
      - run: yarn nx affected -t build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} 
      - run: yarn nx affected -t docker --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} 

  deploy:
    name: Deploy apps
    runs-on: ubuntu-latest
    needs: 'build'
    steps:
      - name: Copy docker compose
        uses: appleboy/scp-action@v0.1.7
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: 'docker-compose.yml'
          target: /home/${{ secrets.SSH_USERNAME }}/projects/voecom

      - name: Run containers
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

            docker pull anclaev/voecom-core:latest
            docker pull anclaev/voecom-auth:latest

            cd /home/${{ secrets.SSH_USERNAME }}/projects/voecom

            docker-compose -p "voecom" down
            docker-compose -p "voecom" up -d
